name: Build, push and release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'New release git/docker tag to publish'
        required: true
        type: string
      ingress_gce_version:
        description: 'kubernetes/ingress-gce version to checkout on build'
        required: true
        type: string

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_REPO: gardener/ingress-gce
  IMAGE_TAG: ${{ inputs.release_tag }}
  PLATFORMS: linux/amd64,linux/arm64

defaults:
  run:
    shell: bash

jobs:
  build-push-release:
    permissions:
      # give GITHUB_TOKEN write permissions
      packages: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the gardener/ingress-gce repository
        uses: actions/checkout@v4

      - name: Checkout the kubernetes/ingress-gce repository
        uses: actions/checkout@v4
        with:
          repository: 'kubernetes/ingress-gce'
          path: './ingress-gce'
          persist-credentials: false
          ref: '${{ inputs.ingress_gce_version }}'

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          push: true
          platforms: ${{ env.PLATFORMS }}

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release_tag }}
          makeLatest: true
          body: |
            ## Docker Images
            * ingress-gce: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
